### ISSUE TITLE
Lora support

### ISSUE THREAD

**Issue by culda** [yishaoai/flux-controlnet-inpaint#2]
Does the model support loras? 
How can we train the model on a particular clothing item or scene?

**Comment by datong-new** [comment]
I think we can load lora into the flux model like this (But I have not test it)
```python
pipe.load_lora_weights("/data/lora.safetensors")
```

Besides, you can train a new controlnet model following the tutorial: https://github.com/yishaoai/tutorials-of-100-wonderful-ai-models/tree/main/2.flux-controlnet
